### ISSUE TITLE
V download.html po vybraní platformy vypýtať "secret key" (kľúč vygenerovaný adminmi) a až potom pustiť ku sťahovaniu

### ISSUE THREAD

**Issue by oguh43** [filipjenis/Informatika-projekt-HTML#1]
is this necessary? they will have to use one to register an account in the app.

**Comment by filipjenis** [comment]
Tento bod bol zrušený. 
Dôvody:
1. Táto časť nie je potrebná, nakoľko kontrola bude prebiehať v samotnej aplikácii Makeshift Technic (stránka je o reálnom budúcom projekte)
2. Aj keby kontrola cez stránku nebola duplicitná, časová tieseň by nás ovplyvnila a naše riešenie by nebolo na 100% podľa našich predstáv

**Comment by oguh43** [comment]
Nádherne povedané @filipjenis
