### ISSUE TITLE
Admin dashboard (zobrazovanie ticketov z contact.html)

### ISSUE THREAD

**Issue by oguh43** [filipjenis/Informatika-projekt-HTML#2]
listovanie ticketov, a prehodenie do gmailu (?)

**Comment by filipjenis** [comment]
@oguh43 už by sme mali začať robiť na tejto časti 😄

**Comment by oguh43** [comment]
Meh

**Comment by filipjenis** [comment]
Uno reverse

**Comment by oguh43** [comment]
:(

**Comment by filipjenis** [comment]
It's in the plan, so you have to do it

**Comment by oguh43** [comment]
:(

**Comment by filipjenis** [comment]
![hugo](https://user-images.githubusercontent.com/52507156/116007779-ac483400-a611-11eb-823e-bb95762424bb.png)

**Comment by oguh43** [comment]
Well, now there is no way back :(
