### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by oguh43** [filipjenis/Informatika-projekt-HTML#6]
Requires https://github.com/filipjenis/Informatika-projekt-HTML/issues/5 to be finished. Mainly adminPanel.html

**Comment by filipjenis** [comment]
#5 will be finished during the day. Will make it my no.1 priority. 🙂

**Comment by filipjenis** [comment]
@oguh43 #5 is kinda finished in 62f127e
filterSelection() will be added later

**Comment by oguh43** [comment]
Done in https://github.com/filipjenis/Informatika-projekt-HTML/commit/ad9e8f43e93af35a33a790536393a4f704fd8a21
