### ISSUE TITLE
Add session script manager to all html files

### ISSUE THREAD

**Issue by oguh43** [filipjenis/Informatika-projekt-HTML#7]
Last thing to do.

**Comment by oguh43** [comment]
Added https://github.com/filipjenis/Informatika-projekt-HTML/commit/d9bb5b36aa71e1ef62fea94e64b666534de87d27

**Comment by filipjenis** [comment]
Very well :+1:

**Comment by oguh43** [comment]
Only missing `adminPanel.html` (#6 #5)

**Comment by oguh43** [comment]
Finished by @filipjenis
